train:
  - _target_: src.metrics.ArgmaxCERMetric
    name: "CER_(Argmax)"
  - _target_: src.metrics.ArgmaxWERMetric
    name: "WER_(Argmax)"

inference:
  - _target_: src.metrics.ArgmaxCERMetric
    name: "CER_(Argmax)"
  - _target_: src.metrics.ArgmaxWERMetric
    name: "WER_(Argmax)"
  - _target_: src.metrics.BeamSearchCERMetric
    name: "CER_(BeamSearch)"
    nbest: 16
    beam_size: 16
    type: "torch"
  - _target_: src.metrics.BeamSearchWERMetric
    name: "WER_(BeamSearch)"
    nbest: 16
    beam_size: 16
    type: "torch"
