train:
  spectrogram:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.batch_transforms.Normalize

inference:
  spectrogram:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.batch_transforms.Normalize
