in_features: 128  # mel filters count
out_features: 28  # vocab len

encoder_layer:
    _target_: torch.nn.TransformerEncoderLayer
    d_model: ${in_features}
    nhead: 8
    dim_feedforward: 1024
    batch_first: True

encoder:
  _target_: torch.nn.TransformerEncoder
  encoder_layer: ${encoder_layer}
  num_layers: 3

classifier:
  _target_: torch.nn.Linear
  in_features: ${in_features}
  out_features: ${out_features}