defaults:
  - model: ctc_model
  - metrics: example
  - datasets: inference
  - dataloader: dataloader
  - transforms: transforms
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  nbest: 4
  beam_size: 4
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "saved/inference/test"
  seed: 1
  from_pretrained: "saved/conf_s_train/checkpoint-epoch50.pth" # path to the pretrained model
