train:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
    n_fft: 200
    n_mels: 50
    f_min: 50
    f_max: 8000
    center: False
  audio: 
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.Gain
        min_gain_in_db: -12.0
        max_gain_in_db: 3.0
        p: 0.33
      - _target_: src.transforms.wav_augs.Pitch
        sample_rate: 16000
        min_transpose_semitones: -4.0 
        max_transpose_semitones: 4.0
        p: 0.33
      - _target_: src.transforms.wav_augs.Noise
        loc: 0.0
        scale: 0.005
        p: 0.33
      - _target_: src.transforms.wav_augs.BandPassFilter
        sample_rate: 16000
        min_center_frequency: 200
        max_center_frequency: 4000
        min_bandwidth_fraction: 1.0
        max_bandwidth_fraction: 1.99
        p: 0.1

inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
